name: Publish

on:
    pull_request:
        types: [closed]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@mapgrid'
            - run: yarn install
            - run: yarn run build
            - run: yarn run track
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
